apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: httproute
prefix: slingshot-
fieldSpecs:
  - path: spec/parentRefs/name
    kind: HTTPRoute
  - path: spec/rules/backendRefs/name
    kind: HTTPRoute